title: Quantenchemie
author: Roland Mitric
logo: logo.png

execute:
  execute_notebooks: force
  timeout: 320
  allow_errors: false

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/rolandmitric/quantum_chemistry_2025
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  extra_css: [_static/custom.css]
  use_thebe: true

launch_buttons:
  binderhub_url: https://mybinder.org
  notebook_interface: jupyterlab
  thebe: true

thebe:
  binder:
    url: https://mybinder.org
    repo: rolandmitric/quantum_chemistry_2025
    ref: main
  kernelName: python3
  requestKernel: true

