# =========================
# Jupyter Book: _config.yml
# =========================

# Book settings
title: Quantenchemie
author: Roland Mitric
logo: logo.png

# Notebook execution (build-time)
execute:
  execute_notebooks: force
  timeout: 120
  allow_errors: false

# LaTeX/PDF
latex:
  latex_documents:
    targetname: book.tex

# Citations
bibtex_bibfiles:
  - references.bib

# GitHub repository (must match your public repo)
repository:
  url: https://github.com/rolandmitric/quantum_chemistry_2025
  branch: main

# HTML options
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
  use_thebe: false   # keep OFF for reliability

# Launch buttons (Binder only; opens full notebooks)
launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: false

# Sphinx config (minimal; no Thebe overrides)
sphinx:
  config:
    html_theme_options:
      use_download_button: true

# Cell tag rules
tags:
  remove_input_tags: ["remove-input"]
  hide_input_tags: ["hide-input"]
  remove_output_tags: ["remove-output"]
  remove_cell_tags: ["remove-cell"]

