# Book settings
title: Quantenchemie
author: Roland Mitric
logo: logo.png

# Notebook execution (build-time)
execute:
  execute_notebooks: force
  timeout: 120
  allow_errors: false

# LaTeX output
latex:
  latex_documents:
    targetname: book.tex

# Citations
bibtex_bibfiles:
  - references.bib

# GitHub repository (must match your public repo)
repository:
  url: https://github.com/rolandmitric/quantum_chemistry_2025
  branch: main

# HTML + Thebe
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
  use_thebe: true

# Launch buttons (Binder for Thebe back-end)
launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true

# Sphinx/Thebe configuration
sphinx:
  config:
    thebe_config:
      binderhub_url: https://mybinder.org
      repository_url: https://github.com/rolandmitric/quantum_chemistry_2025
      repository_branch: main
      kernel_options:
        name: python3
      # (Optional) widget preloads if you use ipywidgets / matplotlib widgets:
      preloads:
        - https://unpkg.com/@jupyter-widgets/html-manager@^1.0.0/dist/index.js
        - https://unpkg.com/jupyter-matplotlib@^0.11.3/dist/index.js

# Cell tag rules
tags:
  remove_input_tags: ["remove-input"]
  hide_input_tags: ["hide-input"]
  remove_output_tags: ["remove-output"]
  remove_cell_tags: ["remove-cell"]

