# Book settings
title: Quantenchemie
author: Roland Mitric
logo: logo.png

# Notebook execution
execute:
  execute_notebooks: force
  timeout: 120
  allow_errors: false

# LaTeX output
latex:
  latex_documents:
    targetname: book.tex

# Citations
bibtex_bibfiles:
  - references.bib

# Repository (must match your public GitHub repo)
repository:
  url: https://github.com/rolandmitric/quantum_chemistry_2025
  branch: main   # change if your default is 'master'

# HTML config
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
  use_thebe: true

# Launch buttons (Thebe + Binder)
launch_buttons:
  binderhub_url: https://mybinder.org
  thebe: true

# Sphinx/Thebe configuration  (← no leading space!)
sphinx:
  config:
    thebe_config:
      binderhub_url: https://mybinder.org
      repository_url: https://github.com/rolandmitric/quantum_chemistry_2025
      repository_branch: HEAD          # robust against main/master mismatch
      kernel_options:
        name: python3
      preloads:
        # Widget manager (required for ANY ipywidget)
        - https://unpkg.com/@jupyter-widgets/html-manager@^1.0.0/dist/index.js
        # Matplotlib widget front-end (required for %matplotlib widget)
        - https://unpkg.com/jupyter-matplotlib@^0.11.3/dist/index.js

# Cell tag rules
tags:
  remove_input_tags: ["remove-input"]
  hide_input_tags: ["hide-input"]
  remove_output_tags: ["remove-output"]
  remove_cell_tags: ["remove-cell"]

