title: Quantenchemie
author: Roland Mitric

execute:
  execute_notebooks: "off"

html:
  use_thebe: true
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

# Rocket appears if binderhub_url is set here
launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
  notebook_interface: jupyterlab

# Must be the SOURCE repo (not gh-pages)
repository:
  url: https://github.com/rolandmitric/quantum_chemistry_2025
  branch: main
  path_to_book: ""   # set to subfolder if the book lives in one

# This block prevents the sphinx-thebe NoneType error
thebe:
  binder:
    repo_url: https://github.com/rolandmitric/quantum_chemistry_2025
    ref: main
  kernel_name: python3

sphinx:
  config:
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
    html_theme_options:
      secondary_sidebar_items: ["page-toc"]
      show_toc_level: 3

