name: qc-book
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyter
  - notebook          # classic server (what Thebe talks to)
  - jupyterlab        # optional, for Binder Lab button
  - numpy
  - sympy
  - matplotlib
  - ipywidgets>=8
  - ipympl=0.9.7      # if you want `%matplotlib widget`; remove if not needed

