name: qc-book
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyter            # meta: notebook + server + console
  - notebook
  - numpy
  - sympy
  - matplotlib
  - ipywidgets>=8
  - pip
  - pip:
      - ipympl==0.11.3   # matches your Thebe preload

