name: qc-book
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - sympy
  - matplotlib
  - ipywidgets>=8
  - ipympl                # for %matplotlib widget
  - jupyterlab
  - notebook              # Binder uses classic notebook backend
  - ipympl=0.11.3      # backend for %matplotlib widget
  - jupyterlab_widgets    # ensures widgets render correctly
  - jupyter-book          # optional but keeps environment reproducible
  - nbconvert
  - pip
  - pip:
      - thebe             # lightweight front-end dependency
